In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(5,5,1)

    def forward(self, x):
        x = self.conv1(x)
        return x


yoloprev=Model()
diffusion=Model()
yoloaft=Model()
for param in yoloaft.parameters():
    param.requires_grad=False

In [3]:

x_leaf = torch.ones(1,5,1,1, requires_grad = True)
x_blur_leaf = torch.ones(1,5,1,1, requires_grad = True)+1

with torch.no_grad():
    x_latent = yoloprev(x_leaf)
    x_blur_latent = yoloprev(x_blur_leaf)
    
x_blur_rev = diffusion(x_blur_latent)

loss_latent = (x_latent - x_blur_rev).abs().mean()
print(loss_latent)
    

loss_latent.backward()
print(x_leaf.requires_grad)
print(x_blur_leaf.requires_grad)
print('loss_latent.grad_fn = '+str(loss_latent.grad_fn))
print('x_leaf.grad = '+str(x_leaf.grad))
print('x_blur_leaf.grad = '+str(x_blur_leaf.grad))



print('-----yoloprev-----')
for name, param in yoloprev.named_parameters():
    print(name)
    #print(param)
    print(param.requires_grad)
    print(param.grad)
    
print('-----diffusion-----')
for name, param in diffusion.named_parameters():
    print(name)
    #print(param)
    print(param.requires_grad)
    print(param.grad)
    
print('-----yoloaft-----')
for name, param in yoloaft.named_parameters():
    print(name)
    #print(param)
    print(param.requires_grad)
    print(param.grad)
#backward()
#print('data.grad = '+str(data.grad))
#print('x1.grad = '+str(x1.grad))
#print('x2.grad = '+str(x2.grad))
#print('x3.grad = '+str(x3.grad))
#print('z.grad = '+str(z.grad))


tensor(0.8985, grad_fn=<MeanBackward0>)
True
True
loss_latent.grad_fn = <MeanBackward0 object at 0x7f3cb821dfd0>
x_leaf.grad = None
x_blur_leaf.grad = None
-----yoloprev-----
conv1.weight
True
None
conv1.bias
True
None
-----diffusion-----
conv1.weight
True
tensor([[[[-0.4255]],

         [[-0.1143]],

         [[ 0.4212]],

         [[-0.0783]],

         [[-0.0706]]],


        [[[ 0.4255]],

         [[ 0.1143]],

         [[-0.4212]],

         [[ 0.0783]],

         [[ 0.0706]]],


        [[[ 0.4255]],

         [[ 0.1143]],

         [[-0.4212]],

         [[ 0.0783]],

         [[ 0.0706]]],


        [[[-0.4255]],

         [[-0.1143]],

         [[ 0.4212]],

         [[-0.0783]],

         [[-0.0706]]],


        [[[ 0.4255]],

         [[ 0.1143]],

         [[-0.4212]],

         [[ 0.0783]],

         [[ 0.0706]]]])
conv1.bias
True
tensor([-0.2000,  0.2000,  0.2000, -0.2000,  0.2000])
-----yoloaft-----
conv1.weight
True
None
conv1.bias
True
None


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:19: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.


In [3]:
x_leaf = torch.ones(1,5,1,1, requires_grad = True)
x_blur_leaf = torch.ones(1,5,1,1, requires_grad = True)+1

with torch.no_grad():
    x_latent = yoloprev(x_leaf)
    x_blur_latent = yoloprev(x_blur_leaf)
    
x_blur_rev = diffusion(x_blur_latent)

#loss_latent = (x_latent - x_blur_rev).abs().mean()
x_aft_latent = yoloaft(x_latent)
x_blur_aft_latent = yoloaft(x_blur_rev)
loss_latent = (x_latent - x_blur_rev).abs().mean()+(x_aft_latent - x_blur_aft_latent).abs().mean()
loss_latent.backward()
print('-----yoloprev-----')
for name, param in yoloprev.named_parameters():
    print(name)
    #print(param)
    print(param.requires_grad)
    print(param.grad)
    
print('-----diffusion-----')
for name, param in diffusion.named_parameters():
    print(name)
    #print(param)
    print(param.requires_grad)
    print(param.grad)
    
print('-----yoloaft-----')
for name, param in yoloaft.named_parameters():
    print(name)
    #print(param)
    print(param.requires_grad)
    print(param.grad)


-----yoloprev-----
conv1.weight
True
None
conv1.bias
True
None
-----diffusion-----
conv1.weight
True
tensor([[[[-0.2731]],

         [[-0.2100]],

         [[ 0.1401]],

         [[-0.0034]],

         [[-0.0205]]],


        [[[ 0.4191]],

         [[ 0.3222]],

         [[-0.2150]],

         [[ 0.0053]],

         [[ 0.0314]]],


        [[[-0.2096]],

         [[-0.1611]],

         [[ 0.1075]],

         [[-0.0026]],

         [[-0.0157]]],


        [[[-0.3041]],

         [[-0.2338]],

         [[ 0.1560]],

         [[-0.0038]],

         [[-0.0228]]],


        [[[ 0.2802]],

         [[ 0.2154]],

         [[-0.1437]],

         [[ 0.0035]],

         [[ 0.0210]]]])
conv1.bias
True
tensor([ 0.2693, -0.4132,  0.2066,  0.2998, -0.2762])
-----yoloaft-----
conv1.weight
False
None
conv1.bias
False
None
